package_update: true
packages: [certbot]
write_files:
- path: /etc/systemd/resolved.conf
  append: true
  content: |
    MulticastDNS=yes

- path: /etc/systemd/system/mdns@.service
  content: |
    [Service]
    Type=oneshot
    ExecStart=/usr/bin/systemd-resolve --set-mdns=yes --interface=%i
    After=sys-subsystem-net-devices-%i.device

    [Install]
    WantedBy=sys-subsystem-net-devices-%i.device

runcmd:
- systemctl restart systemd-resolved.service
- "for interface in $(ip -o link show | awk -F': ' '{print $2}' | grep -v lo); do systemctl start mdns@$interface.service; done"
- "for interface in $(ip -o link show | awk -F': ' '{print $2}' | grep -v lo); do systemctl enable mdns@$interface.service; done"
